<a href="https://colab.research.google.com/github/gsgh3016/1st_semester/blob/main/Gamchan/chap11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 11-01 단어의 표현 방법
## 1. 단어의 표현 방법

**국소 표현(Local Representation) aka 이산 표현(Discrete Representation)방법**: 해당 값만 참고 &rarr; 특정 값 매핑

**분산 표현(Distributed Representation) aka 연속 표현(Continuous Represnetation) 방법**: 단어 주변을 참고하여 표현

ex)
> puppy, cute, lovely

Local Representation: ex) 각 단어 별 숫자 매핑 &rarr; 의미, 뉘앙스 표현 X

Distributed Representation: ex) puppy는 cute, lovely하다.

## 2. 단어 표현의 카테고리화

![](https://wikidocs.net/images/page/31767/wordrepresentation.PNG)

# 11-02 백 오브 워즈(Bag of Words) 방법

## 1. Bag of Words(BoW)란?

1. 텍스트 전부 가방에 넣기: 각 단어에 고유한 정수 인덱스를 부여합니다.(단어 집합 생성)
2. 가방 흔들어 섞기(순서는 더 이상 X): 각 인덱스의 위치에 단어 토큰의 등장 횟수를 기록한 벡터를 만듭니다.

In [ ]:
!pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 83.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 37.5 MB/s eta 0:00:00


In [ ]:
from konlpy.tag import Okt

okt = Okt()

def build_bag_of_words(document):
  # 온점 제거 및 형태소 분석
  document = document.replace('.', '')
  tokenized_document = okt.morphs(document)

  word_to_index = {}
  bow = []

  for word in tokenized_document:
    if word not in word_to_index.keys():
      word_to_index[word] = len(word_to_index)
      # BoW에 전부 기본값 1을 넣는다.
      bow.insert(len(word_to_index) - 1, 1)
    else:
      # 재등장하는 단어의 인덱스
      index = word_to_index.get(word)
      # 재등장한 단어는 해당하는 인덱스의 위치에 1을 더한다.
      if index is None:
        print(f"해당 단어: {word}는 존재하지 않습니다.")
        return None, None
      bow[index] = bow[index] + 1

  return word_to_index, bow


In [ ]:
doc1 = "정부가 발표하는 물가상승률과 소비자가 느끼는 물가상승률은 다르다."
vocab, bow = build_bag_of_words(doc1)
print('vocabulary :', vocab)
print('bag of words vector :', bow)


vocabulary : {'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9}
bag of words vector : [1, 2, 1, 1, 2, 1, 1, 1, 1, 1]


## 2. Bag of Words의 다른 예제들

In [ ]:
doc2 = '소비자는 주로 소비하는 상품을 기준으로 물가상승률을 느낀다.'

vocab, bow = build_bag_of_words(doc2)
print('vocabulary :', vocab)
print('bag of words vector :', bow)


vocabulary : {'소비자': 0, '는': 1, '주로': 2, '소비': 3, '하는': 4, '상품': 5, '을': 6, '기준': 7, '으로': 8, '물가상승률': 9, '느낀다': 10}
bag of words vector : [1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1]


In [ ]:
doc3 = doc1 + ' ' + doc2
vocab, bow = build_bag_of_words(doc3)
print('vocabulary :', vocab)
print('bag of words vector :', bow)


vocabulary : {'정부': 0, '가': 1, '발표': 2, '하는': 3, '물가상승률': 4, '과': 5, '소비자': 6, '느끼는': 7, '은': 8, '다르다': 9, '는': 10, '주로': 11, '소비': 12, '상품': 13, '을': 14, '기준': 15, '으로': 16, '느낀다': 17}
bag of words vector : [1, 2, 1, 2, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1]


## 3. CountVectorizer 클래스로 BoW 만들기


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ['you know I want your love. because I love you.']
vector = CountVectorizer()

# 코퍼스로부터 각 단어의 빈도수를 기록
print('bag of words vector :', vector.fit_transform(corpus).toarray())

# 각 단어의 인덱스가 어떻게 부여되었는지를 출력
print('vocabulary :',vector.vocabulary_)


bag of words vector : [[1 1 2 1 2 1]]
vocabulary : {'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}


you와 love는 두 번씩 언급 &rarr; [[1 1 2 1 2 1]]

CountVectorizer는 띄어쓰기를 기준으로 분리

## 4. 불용어를 제거한 BoW 만들기

### (1) 사용자가 직접 정의한 불용어 사용

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords


In [ ]:
text = ["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words=["the", "a", "an", "is", "not"])
print('bag of words vector :',vect.fit_transform(text).toarray())
print('vocabulary :',vect.vocabulary_)


bag of words vector : [[1 1 1 1 1]]
vocabulary : {'family': 1, 'important': 2, 'thing': 4, 'it': 3, 'everything': 0}


### (2) CountVectorizer에서 제공하는 자체 불용어 사용


In [ ]:
text = ["Family is not an important thing. It's everything."]
vect = CountVectorizer(stop_words="english")
print('bag of words vector :',vect.fit_transform(text).toarray())
print('vocabulary :',vect.vocabulary_)


bag of words vector : [[1 1 1]]
vocabulary : {'family': 0, 'important': 1, 'thing': 2}


### (3) NLTK에서 지원하는 불용어 사용


In [ ]:
import nltk
nltk.download('stopwords')

text = ["Family is not an important thing. It's everything."]
stop_words = stopwords.words("english")
vect = CountVectorizer(stop_words=stop_words)
print('bag of words vector :',vect.fit_transform(text).toarray())
print('vocabulary :',vect.vocabulary_)


bag of words vector : [[1 1 1 1]]
vocabulary : {'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


# 11-03 문서의 벡터화: 문서 단어 행렬(Document-Term Matrix, DTM)

문서 단어 행렬(Document-Term Matrix, DTM): 서로 다른 문서들의 BoW들을 결합한 표현 방법. Transpose시 TDM

## 1. 문서 단어 행렬(Document-Term Matrix, DTM)의 표기법

> 문서1 : 먹고 싶은 사과<br>
> 문서2 : 먹고 싶은 바나나<br>
> 문서3 : 길고 노란 바나나 바나나<br>
> 문서4 : 저는 과일이 좋아요

|       | 과일이 | 길고 | 노란 | 먹고 | 바나나 | 사과 | 싶은 | 저는 | 좋아요 |
|-------|--------|------|------|------|--------|------|------|------|--------|
| 문서1 | 0      | 0    | 0    | 1    | 0      | 1    | 1    | 0    | 0      |
| 문서2 | 0      | 0    | 0    | 1    | 1      | 0    | 1    | 0    | 0      |
| 문서3 | 0      | 1    | 1    | 0    | 2      | 0    | 0    | 0    | 0      |
| 문서4 | 1      | 0    | 0    | 0    | 0      | 0    | 0    | 1    | 1      |

## 2. 문서 단어 행렬(Document-Term Matrix)의 한계

### 1) 희소 표현(Sparse representation)
- 메모리 공간 낭비, 계산 리소스 증가 like 원-핫 벡터 ($\because$ 하나 빼고 대부분의 값이 0)
- 희소 벡터(sparse vector), 희소 행렬(sparse matrix): 대부분의 값이 0인 표현(DTM도 이에 해당) &rarr; 많은 저장 공간, 높은 계산 복잡도 요구

### 2) 단순 빈도 수 기반 접근
- 불용어의 경우, 문서 상관 없이 많이 등장
- 문서에서 중요한 단어 vs 불필요한 단어 구분 필요


# 11-04 TF-IDF(Term Frequency-Inverse Document Frequency)


## 1. TF-IDF(단어 빈도-역 문서 빈도, Term Frequency-Inverse Document Frequency)

### (1) tf(d,t) : 특정 문서 d에서의 특정 단어 t의 등장 횟수. &rarr; 결국 DTM

### (2) df(t) : 특정 단어 t가 등장한 문서의 수. &rarr; only 문서 수

### (3) idf(t) : df(t)에 반비례하는 수.

> \begin{align}
idf(t) = ln(\frac{n}{1+df(t)})
\end{align}

- df(t)가 작을 경우 너무 커짐
- 희귀 단어에 너무 많은 가중치 부여
- 분모에 1 + : 분모 0 방지
- 보통 자연 로그 사용

TF-IDF: tf x idf &rarr; idf를 곱해줌으로써 여러 문서에 등장하는 단어의 가중치 낮춤


## 2. 파이썬으로 TF-IDF 직접 구현하기

In [ ]:
import pandas as pd # 데이터프레임 사용을 위해
from math import log # IDF 계산을 위해

docs = [
  '먹고 싶은 사과',
  '먹고 싶은 바나나',
  '길고 노란 바나나 바나나',
  '저는 과일이 좋아요'
]
vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()


In [ ]:
# 총 문서의 수
N = len(docs)

def tf(t, d):
  return d.count(t)

def idf(t):
  df = 0
  for doc in docs:
    df += t in doc
  return log(N/(df+1))

def tfidf(t, d):
  return tf(t,d)* idf(t)


In [ ]:
result = []

# 각 문서에 대해서 아래 연산을 반복
for i in range(N):
  result.append([])
  d = docs[i]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(tf(t, d))

tf_ = pd.DataFrame(result, columns = vocab)
tf_


과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
0    0   0   0   1    0   1   1   0    0
1    0   0   0   1    1   0   1   0    0
2    0   1   1   0    2   0   0   0    0
3    1   0   0   0    0   0   0   1    1

In [ ]:
result = []
for j in range(len(vocab)):
    t = vocab[j]
    result.append(idf(t))

idf_ = pd.DataFrame(result, index=vocab, columns=["IDF"])
idf_


IDF
과일이  0.693147
길고   0.693147
노란   0.693147
먹고   0.287682
바나나  0.287682
사과   0.693147
싶은   0.287682
저는   0.693147
좋아요  0.693147

In [ ]:
result = []
for i in range(N):
  result.append([])
  d = docs[i]
  for j in range(len(vocab)):
    t = vocab[j]
    result[-1].append(tfidf(t,d))

tfidf_ = pd.DataFrame(result, columns = vocab)
tfidf_


과일이        길고        노란        먹고       바나나        사과        싶은  \
0  0.000000  0.000000  0.000000  0.287682  0.000000  0.693147  0.287682   
1  0.000000  0.000000  0.000000  0.287682  0.287682  0.000000  0.287682   
2  0.000000  0.693147  0.693147  0.000000  0.575364  0.000000  0.000000   
3  0.693147  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

         저는       좋아요  
0  0.000000  0.000000  
1  0.000000  0.000000  
2  0.000000  0.000000  
3  0.693147  0.693147

## 3. 사이킷런을 이용한 DTM과 TF-IDF 실습

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',
]

vector = CountVectorizer()

# 코퍼스로부터 각 단어의 빈도수를 기록
print(vector.fit_transform(corpus).toarray())

# 각 단어와 맵핑된 인덱스 출력
print(vector.vocabulary_)


[[0 1 0 1 0 1 0 1 1]
 [0 0 1 0 0 0 0 1 0]
 [1 0 0 0 1 0 1 0 0]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',
]

tfidfv = TfidfVectorizer().fit(corpus)
print(tfidfv.transform(corpus).toarray())
print(tfidfv.vocabulary_)


[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


# 11-05 코사인 유사도를 이용한 추천 시스템

## 1. 코사인 유사도(Cosine Similarity)

> \begin{align}
similarity=cos(Θ)=\frac{A⋅B}{||A||\ ||B||}=\frac{\sum_{i=1}^{n}{A_{i}×B_{i}}}{\sqrt{\sum_{i=1}^{n}(A_{i})^2}×\sqrt{\sum_{i=1}^{n}(B_{i})^2}}
\end{align}

In [ ]:
# 문서 벡터 간 코사인 유사도(DTM)
import numpy as np
from numpy import dot
from numpy.linalg import norm

def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))

doc1 = np.array([0,1,1,1])
doc2 = np.array([1,0,1,1])
doc3 = np.array([2,0,2,2])

print(f"문서 1과 문서2의 유사도 :{cos_sim(doc1, doc2): .2f}")
print(f"문서 1과 문서3의 유사도 :{cos_sim(doc1, doc3): .2f}")
print(f"문서 2와 문서3의 유사도 :{cos_sim(doc2, doc3): .2f}")


문서 1과 문서2의 유사도 : 0.67
문서 1과 문서3의 유사도 : 0.67
문서 2와 문서3의 유사도 : 1.00


- 문서 A, B 동일 주제 / 문서 C 다른 주제
- |A| ~= 2|B|, |A| = |C|
- 유클리드 거리로 연산할 시 A,B 유사도 < A,C 유사도일 수 있음
- 코사인 유사도가 더 적합

## 2. 유사도를 이용한 추천 시스템 구현하기

- dataset: https://www.kaggle.com/rounakbanik/the-movies-dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/MyDrive/Colab Notebooks/pytorch_practice/dataset/movies_metadata.csv"


MessageError: ignored

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

data = pd.read_csv(file_path, low_memory=False)
data.head(2)


In [ ]:
# 상위 2만개의 샘플을 data에 저장
data = data.head(20000)


In [ ]:
# overview 열에 존재하는 모든 결측값을 전부 카운트하여 출력
print('overview 열의 결측값의 수:',data['overview'].isnull().sum())


In [ ]:
# 결측값을 빈 값으로 대체
data['overview'] = data['overview'].fillna('')


In [ ]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(data['overview'])
print('TF-IDF 행렬의 크기(shape) :',tfidf_matrix.shape)


In [ ]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
print('코사인 유사도 연산 결과 :',cosine_sim.shape)


In [ ]:
title_to_index = dict(zip(data['title'], data.index))

# 영화 제목 Father of the Bride Part II의 인덱스를 리턴
idx = title_to_index['Father of the Bride Part II']
print(idx)


In [ ]:
def get_recommendations(title, cosine_sim=cosine_sim):
    # 선택한 영화의 타이틀로부터 해당 영화의 인덱스를 받아온다.
    idx = title_to_index[title]

    # 해당 영화와 모든 영화와의 유사도를 가져온다.
    sim_scores = list(enumerate(cosine_sim[idx]))

    # 유사도에 따라 영화들을 정렬한다.
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # 가장 유사한 10개의 영화를 받아온다.
    sim_scores = sim_scores[1:11]

    # 가장 유사한 10개의 영화의 인덱스를 얻는다.
    movie_indices = [idx[0] for idx in sim_scores]

    # 가장 유사한 10개의 영화의 제목을 리턴한다.
    return data['title'].iloc[movie_indices]


In [ ]:
get_recommendations('The Dark Knight Rises')


# 11-06 단어와 문서의 유사도를 구하는 다양한 방법

## 1. 유클리드 거리(Euclidean distance)

유클리드 거리는 점들 간의 '실제' 거리를 계산하는 데 사용됩니다. 다차원 공간에서 두 점 사이의 직선 거리를 측정합니다.

### pros

- 직관적인 해석: 공간에서의 실제 거리를 나타내므로 이해하기 쉽습니다.
- 계산이 간단: 두 점 간의 거리를 계산하는 공식이 단순합니다.

### cons

- 차원의 저주: 고차원 데이터에서 성능이 저하될 수 있습니다. 각 특성의 중요성이 동일하게 고려되기 때문입니다.
- 크기에 민감: 문서의 길이가 다르면, 유사도가 왜곡될 수 있습니다.

## 2. 자카드 유사도(Jaccard similarity)

자카드 유사도는 두 집합 간의 유사도를 측정합니다. 교집합의 크기를 합집합의 크기로 나눈 값입니다.

### pros

- 크기에 덜 민감: 자카드 유사도는 집합의 크기에 영향을 덜 받습니다.
- 중복의 영향을 덜 받음: 같은 요소가 여러 번 등장해도 한 번만 계산됩니다.

### cons

- 희소성의 영향: 매우 희소한 데이터에서는 자카드 유사도가 낮게 나타날 수 있습니다.
- 정보 손실: 벡터의 크기나 정보량은 고려되지 않으며, 오직 집합의 구성요소만 고려됩니다.